apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-app
  labels:
    app: agent-app
  annotations:
    version: "v2" # Added to trigger a new revision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-app
  template:
    metadata:
      labels:
        app: agent-app
    spec:
      containers:
        - name: agent-app
          image: nginx:latest
          ports:
            - containerPort: 80
