apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: primaryEncryptionKey
    secretKeyRef:
      name: encryption-key # This name must match the metadata.name of the Secret below
      key: key            # This key must match the key name in the Secret's data section