apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: message-subscription
  namespace: default
spec:
  pubsubname: pubsub
  topic: message-updated
  routes:
    rules:
      - match: event.type == "update"
        path: /subscribe

