apiVersion: v1
kind: Service
metadata:
  name: daca-ai-app
  namespace: default  # Explicit for clarity
  labels:
    app: daca-ai-app
spec: 
  selector:
    app: daca-ai-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      appProtocol: http
  type: ClusterIP