apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: message-subscription
spec:
  pubsubname: daca-pubsub
  topic: user-chat
  routes:
    default: /subscribe
    rules:
      - match: event.type == "update"
        path: /subscribe


# https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/