apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-app
  namespace: default  # Explicit for clarity or Omit and specify via kubectl -n default
spec:
  replicas: 1 # Increase to 2-3 for production
  selector:
    matchLabels:
      app: pubsub-app
  template:
    metadata:
      labels:
        app: pubsub-app
      annotations: 
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsub-app"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "info"
    spec:
      containers:
      - name: app
        image: pubsub-lab-app # CORRECTED: Match the Tiltfile ref
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
