[project]
name = "ambient-actor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Junaid", email = "mr.junaidshaukat@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dapr>=1.15.0",
    "dapr-ext-fastapi>=1.15.0",
    "fastapi[standard]>=0.115.12",
]

[project.scripts]
ambient-actor = "ambient_actor:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
