apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-actor-app
  namespace: default  # Explicit for clarity or Omit and specify via kubectl -n default
spec:
  replicas: 1 # Increase to 2-3 for production
  selector:
    matchLabels:
      app: hello-actor-app
  template:
    metadata:
      labels:
        app: hello-actor-app
      annotations: 
        dapr.io/enabled: "true"
        dapr.io/app-id: "hello-actor-app"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "info"
    spec:
      containers:
      - name: app
        image: hello-actor-app # CORRECTED: Match the Tiltfile ref
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-actor-app-service
  namespace: default
  labels:
    app: hello-actor-app
spec: 
  selector:
    app: hello-actor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      appProtocol: http
  type: ClusterIP