apiVersion: v1
kind: Service
metadata:
  name: dapr-fastapi-hello
  namespace: default
spec:
  selector:
    app: dapr-fastapi-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP