apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: daily-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 */1 * * * *"  # Trigger every minute for testing
  - name: direction
    value: input