[project]
name = "agent-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langsmith[openai-agents]>=0.3.42",
    "langtrace-python-sdk>=3.8.18",
    "openai-agents>=0.0.15",
]
